spec:
  template:
    spec:
      volumes:
        - configMap:
            name: reactica-config
            optional: true
            items:
            - key: application.yaml
              path: config.yml
          name: config
      containers:
        - env:
            - name: VERTX_CONFIG_PATH
              value: '/deployments/conf/config.yml'
          volumeMounts:
            - name: config
              mountPath: /deployments/conf

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
